@startuml
title Diagrama de Casos de Uso

left to right direction
actor "Aluno" as Aluno
actor "Professor" as Professor
actor "Empresa Parceira" as Empresa
actor "Administrador" as Admin
actor "Sistema Email" as Email

rectangle  {
  usecase "Cadastrar-se (Aluno)" as UC1
  usecase "Login/Autenticação" as UC2
  usecase "Consultar Extrato" as UC3A
  usecase "Enviar Moedas" as UC4
  usecase "Receber Notificação" as UC5
  usecase "Cadastrar Empresa" as UC6
  usecase "Cadastrar Vantagem" as UC7
  usecase "Resgatar Vantagem" as UC8
  usecase "Gerir Instituições/Departamentos" as UC9
  usecase "Creditar Cota Semestral" as UC10
}

Aluno --> UC1
Aluno --> UC2
Aluno --> UC3A
Aluno --> UC8
UC8 --> Email : envia cupom
UC5 <-- Email : notificação

Professor --> UC2
Professor --> UC3A
Professor --> UC4
UC4 --> Email : notifica aluno

Empresa --> UC2
Empresa --> UC6
Empresa --> UC7
Empresa <-- UC8 : recebe email de cupom

Admin --> UC2
Admin --> UC9

@enduml
