#!/usr/bin/env bash
# Interactive script to create codigo/.env with email settings
# Run locally (will prompt you) and it will write codigo/.env

set -e
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"

echo "This script helps create the file: $ENV_FILE"
echo "It will not print or transmit your credentials. Keep them safe."

echo
read -p "Use Gmail (recommended for quick tests)? [y/N]: " use_gmail
use_gmail=${use_gmail:-n}

if [[ "$use_gmail" =~ ^[Yy] ]]; then
  read -p "Gmail address (GMAIL_USER): " GMAIL_USER
  read -s -p "Gmail App Password (GMAIL_PASS) — will be hidden: " GMAIL_PASS
  echo
  cat > "$ENV_FILE" <<EOF
# Generated by setup_env.sh - DO NOT COMMIT
GMAIL_USER=${GMAIL_USER}
GMAIL_PASS=${GMAIL_PASS}
EMAIL_FROM="MeritCoins <no-reply@${GMAIL_USER#*@}>"
# Optional: NODE_ENV, PORT, DATABASE_URL
# NODE_ENV=development
# PORT=3000
EOF
  echo "Wrote Gmail config to $ENV_FILE"
else
  echo "Enter SMTP server settings (Mailtrap or other provider):"
  read -p "SMTP_HOST: " SMTP_HOST
  read -p "SMTP_PORT (e.g. 587): " SMTP_PORT
  read -p "SMTP_USER: " SMTP_USER
  read -s -p "SMTP_PASS: " SMTP_PASS
  echo
  read -p "Use secure (SSL/TLS) connection? (true/false) [false]: " SMTP_SECURE
  SMTP_SECURE=${SMTP_SECURE:-false}

  cat > "$ENV_FILE" <<EOF
# Generated by setup_env.sh - DO NOT COMMIT
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_SECURE=${SMTP_SECURE}
EMAIL_FROM="MeritCoins <no-reply@your-domain.com>"
# Optional: NODE_ENV, PORT, DATABASE_URL
# NODE_ENV=development
# PORT=3000
EOF
  echo "Wrote SMTP config to $ENV_FILE"
fi

echo
echo "IMPORTANT: Do not commit $ENV_FILE to git. Add it to .gitignore if needed."
echo "Now restart the backend (in the repository root):"
echo "  cd codigo && NODE_ENV=development npm run dev"
echo
echo "After server starts, verify the log shows: EmailService mock mode: false"
echo "Then perform a resgate in the frontend and check your mailbox (or Mailtrap)."

echo
echo "If you want me to also show the coupon in the frontend immediately after resgate, tell me and I can add that UI change."
chmod +x "$ENV_FILE" || true
chmod +x "$ROOT_DIR/setup_env.sh" || true
